# Delete this when you generate a repository from this template
name: Build Infrastructure

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v1.4.0
        with:
          terraform_version: 1.1.5
          terraform_wrapper: false
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: '16.x'
      - run: npm ci
        working-directory: ${{env.working-directory}}
      - run: npm run build:dev
        working-directory: ${{env.working-directory}}
